### ISSUE TITLE
ERROR! Failed to install app '556450' (Disk write failure)

### ISSUE THREAD

**Issue by Freekers** [dickerdockerwalgames/the-forest-dedicated-server-docker#2]
I'm not sure if this is still maintained, but I'm receiving the following error:
```
theforest    | [  0%] Checking for available updates...
theforest    | [----] Verifying installation...
theforest    | Steam Console Client (c) Valve Corporation
theforest    | -- type 'quit' to exit --
theforest    | Loading Steam API...OK.
theforest    |
theforest    | Connecting anonymously to Steam Public...Logged in OK
theforest    | Waiting for user info...OK
theforest    | "@sSteamCmdForcePlatformType" = "windows"
theforest    | ERROR! Failed to install app '556450' (Disk write failure)
theforest    | Error: 8
```

My docker-compose looks as follows:
```
version: '3.7'
services:
  theforest:
    image: theforest_ds:latest
    container_name: theforest
    restart: unless-stopped
    ports:
      - "8766:8766/tcp"
      - "8766:8766/udp"
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27016:27016/tcp"
      - "27016:27016/udp"
    volumes:
      - /opt/the-forest-dedicated-server-docker/server-files:/theforest_ds
      - /opt/the-forest-dedicated-server-docker/config-save-dir:/theforest_ds_config
      - /opt/the-forest-dedicated-server-docker/wine-prefix:/theforest_wineprefix
```  

I'm running the container as root and the volume mounts are owned by root as well. I tried changing the uid and gid to `0`, as that's the uid and gid inside the container, but it made no difference. Any idea what's causing this?
